#!/usr/bin/env bash
# tests/docs-build.sh — drive bin/docs-build against temporary docs folders.
#
# Usage: ./tests/docs-build.sh
#
# Needs uv and pandoc (CI installs both). Every case works in its own temporary folder.
#
# Cases: (1) --init starts docs/ from templates/docs and builds it · (2) --check validates and
# writes nothing · (3) front matter and link errors are reported, and fail the build · (4) included
# examples are refreshed by a build and reported stale by --check · (5) docs_ext.py adds checks, data
# files and site text · (6) any title stays valid YAML and is escaped in the page · (7) --init refuses a folder with Markdown ·
# (8) --view renders Markdown without front matter, links between files, honours --exclude and
# writes only its output · (9) --vendor writes a copy that builds without the template, once
#
# Exit codes: 0 every case passed · 1 a case failed
#
# bash 3.2: no arrays, no mapfile, no ${x^^}.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 1
ROOT="$PWD"
SCRIPT="$ROOT/bin/docs-build"
[ -x "$SCRIPT" ] || { echo "bin/docs-build is not executable" >&2; exit 1; }
for t in uv pandoc; do command -v "$t" > /dev/null || { echo "$t is required" >&2; exit 1; }; done

WORK="$(cd "$(mktemp -d "${TMPDIR:-/tmp}/cc-docs-build-test.XXXXXX")" && pwd -P)"
trap 'rm -rf "$WORK"' EXIT

PASS=0
FAIL=0
ok()  { printf '    ok   %s\n' "$*"; PASS=$((PASS + 1)); }
bad() { printf '    FAIL %s\n' "$*" >&2; FAIL=$((FAIL + 1)); }
check_exit() { if [ "$1" = "$2" ]; then ok "exit $2"; else bad "exit: want $1, got $2"; fi; }
contains() { if grep -qF -- "$2" "$1"; then ok "says: $2"; else bad "$(basename "$1") has no '$2'"; fi; }
lacks() { if grep -qF -- "$2" "$1"; then bad "$(basename "$1") has '$2'"; else ok "no: $2"; fi; }
exists() { if [ -e "$1" ]; then ok "exists: ${1#"$CASE"/}"; else bad "missing: ${1#"$CASE"/}"; fi; }
absent() { if [ -e "$1" ]; then bad "should not exist: ${1#"$CASE"/}"; else ok "absent: ${1#"$CASE"/}"; fi; }
listing() { (cd "$1" && find . -type f | sort); }

n=0
case_new() {
  n=$((n + 1))
  printf '\n(%s) %s\n' "$n" "$1"
  CASE="$WORK/case$n"
  D="$CASE/docs"
  OUT="$CASE/out.txt"
  mkdir -p "$CASE"
}
build() { "$SCRIPT" "$@" > "$OUT" 2>&1; }
start() { build --init "$D" --title "${1:-Widget}" || bad "--init failed: $(cat "$OUT")"; }
# A minimal second document, valid as written.
doc2() {
  cat > "$D/02-api.md" <<EOF
---
id: api
title: API
order: 2
summary: ${1:-The API.}
status: design
updated: 2026-01-01
audience: [engineers]
depends_on: [overview]
related: []
answers:
  - What does the API look like?
---

# API

See [the overview](01-overview.md#scope).

## Endpoints
EOF
}

case_new "--init starts docs/ and builds it"
start "Widget"
check_exit 0 0
for f in README.md AGENTS.md 01-overview.md index.html llms.txt data/manifest.json data/glossary.json; do exists "$D/$f"; done
contains "$D/llms.txt" "# Widget documentation"
contains "$D/llms.txt" "- [01 Overview](01-overview.md):"
lacks "$D/README.md" "__TITLE__"
lacks "$D/README.md" "__DATE__"
if [ "$(jq -r '[.documents[].id] | join(",")' "$D/data/manifest.json")" = "index,overview" ]; then ok "manifest ids"; else bad "manifest: $(jq -c '[.documents[].id]' "$D/data/manifest.json")"; fi
if [ "$(jq -r '.[0].term' "$D/data/glossary.json")" = "Example" ]; then ok "glossary from the terms table"; else bad "glossary: $(cat "$D/data/glossary.json")"; fi
contains "$D/index.html" '<section class="doc" id="overview"'
contains "$D/index.html" "Generated by docs-build"
lacks "$D/index.html" "{{"

case_new "--check validates and writes nothing"
start
doc2
before="$(listing "$D"; cat "$D"/*.md | shasum)"
build --check "$D"
check_exit 0 $?
contains "$OUT" "ok: 3 documents are valid"
if [ "$before" = "$(listing "$D"; cat "$D"/*.md | shasum)" ]; then ok "nothing written"; else bad "--check changed files"; fi

case_new "front matter and link errors fail the build"
start
doc2
perl -0pi -e 's/status: design\n/status: maybe\n/; s/depends_on: \[overview\]/depends_on: [nope]/; s/#scope/#nowhere/' "$D/02-api.md"
printf '\nA [broken link](missing.md).\n' >> "$D/02-api.md"
perl -0pi -e 's/^order: 1\n//m' "$D/01-overview.md"
cp "$D/index.html" "$CASE/index.before"
build "$D"
check_exit 1 $?
contains "$OUT" "02-api.md: status must be one of"
contains "$OUT" "02-api.md: depends_on refers to unknown document id 'nope'"
contains "$OUT" "02-api.md: no heading '#nowhere' in 01-overview.md"
contains "$OUT" "02-api.md: broken link to 'missing.md'"
contains "$OUT" "01-overview.md: front matter is missing 'order'"
if cmp -s "$CASE/index.before" "$D/index.html"; then ok "index.html untouched on failure"; else bad "index.html rewritten despite errors"; fi
sed 's/^id: api$/id: overview/' "$D/02-api.md" > "$CASE/x" && cp "$CASE/x" "$D/02-api.md"
build --check "$D"
contains "$OUT" "document ids are not unique"
rm "$D/README.md"
build --check "$D"
contains "$OUT" "README.md is missing"

case_new "included examples: refreshed by a build, stale under --check"
start
mkdir -p "$D/examples"
printf 'name: first\n' > "$D/examples/pack.yaml"
printf '\n## Example\n\n<!-- include: examples/pack.yaml -->\n<!-- /include -->\n' >> "$D/01-overview.md"
build --check "$D"
check_exit 1 $?
contains "$OUT" "01-overview.md: included examples are stale"
build "$D"
check_exit 0 $?
contains "$D/01-overview.md" "name: first"
contains "$D/01-overview.md" '```yaml'
if jq -e '.examples == ["examples/pack.yaml"]' "$D/data/manifest.json" > /dev/null; then ok "manifest lists examples"; else bad "manifest examples"; fi
printf 'name: second\n' > "$D/examples/pack.yaml"
build --check "$D"
check_exit 1 $?
printf '\n<!-- include: examples/none.yaml -->\n<!-- /include -->\n' >> "$D/01-overview.md"
build "$D"
contains "$OUT" "include target missing: examples/none.yaml"

case_new "docs_ext.py: checks, data files, site text"
start
cat > "$D/docs_ext.py" <<'EOF'
SITE = {"brand": "Widget Co", "tagline": "Design notes", "banner": "Nothing is built yet.",
        "note": "Status: design only.", "links": [["examples/", "examples/"]],
        "examples": [["Pack", "examples/", "an example pack"]]}


def validate(ctx):
    if not any(d["meta"]["id"] == "overview" for d in ctx.docs):
        ctx.error("overview is required")
    if ctx.root.joinpath("FAIL").exists():
        ctx.error("project check failed")


def data(ctx):
    rows = [r for _, rs in ctx.tables_by_section(ctx.docs[0]["body"]) for r in rs]
    return {"tables": {"label": "Tables", "description": "every table row in the index", "data": rows}}
EOF
build "$D"
check_exit 0 $?
exists "$D/data/tables.json"
contains "$D/llms.txt" "- [Tables](data/tables.json): every table row in the index"
contains "$D/llms.txt" "Status: design only. The Markdown files are the source of truth."
contains "$D/llms.txt" "- [Pack](examples/): an example pack"
contains "$D/index.html" '<p class="brand">Widget Co</p>'
contains "$D/index.html" '<p class="banner">Nothing is built yet.</p>'
contains "$D/index.html" '<a href="data/tables.json">data/tables.json</a>'
contains "$OUT" "tables"
touch "$D/FAIL"
build "$D"
check_exit 1 $?
contains "$OUT" "ERROR project check failed"

case_new "a title with quotes, a colon and markup: valid YAML, escaped in the page"
start 'A <b>bold</b> & "quoted": name'
check_exit 0 $?
contains "$D/index.html" "<title>A &lt;b&gt;bold&lt;/b&gt; &amp; &quot;quoted&quot;: name documentation</title>"
contains "$D/index.html" '<p class="brand">A &lt;b&gt;bold&lt;/b&gt; &amp; &quot;quoted&quot;: name documentation</p>'
if [ "$(jq -r .title "$D/data/manifest.json")" = 'A <b>bold</b> & "quoted": name documentation' ]; then ok "title survives the YAML"; else bad "manifest title: $(jq -r .title "$D/data/manifest.json")"; fi

case_new "--init refuses a folder that already has Markdown"
mkdir -p "$D"
echo "# mine" > "$D/notes.md"
build --init "$D" --title X
check_exit 2 $?
contains "$OUT" "already has Markdown files"
if [ "$(listing "$D")" = "./notes.md" ]; then ok "nothing added"; else bad "files: $(listing "$D")"; fi

case_new "--view: any Markdown, links between files, --exclude, one output"
R="$CASE/repo"
mkdir -p "$R/docs/machines" "$R/templates/x" "$R/.hidden"
printf '# The repo\n\nTop-level readme. See [the fleet](docs/FLEET.md#rules).\n' > "$R/README.md"
printf '# Fleet\n\nEvery machine.\n\n## Rules\n\nRead [air](machines/air.md) and [a script](../bin/tool).\n' > "$R/docs/FLEET.md"
printf -- '---\nage_recipient: age1xyz\n---\n\n# air\n\nThe laptop.\n' > "$R/docs/machines/air.md"
printf '# Template\n' > "$R/templates/x/README.md"
printf '# Hidden\n' > "$R/.hidden/x.md"
before="$(listing "$R")"
build --view "$R" --exclude 'templates/**' --title "Repo view"
check_exit 0 $?
V="$R/.docs-view/index.html"
exists "$V"
contains "$OUT" "(3 documents)"
contains "$V" '<section class="doc" id="docs-fleet"'
contains "$V" 'href="#docs-machines-air"'
contains "$V" 'href="#docs-fleet-rules"'
contains "$V" 'href="../bin/tool"'
contains "$V" '<p class="side-title">docs/machines/</p>'
contains "$V" "The laptop."
lacks "$V" "age_recipient"
lacks "$V" "# Template"
lacks "$V" "Hidden"
if [ "$(listing "$R" | grep -v '^./.docs-view/')" = "$before" ]; then ok "only .docs-view/ written"; else bad "the view changed other files"; fi
build --view "$R" --out "$CASE/elsewhere/view.html"
exists "$CASE/elsewhere/view.html"
contains "$CASE/elsewhere/view.html" 'href="../repo/docs/FLEET.md"'

case_new "--vendor: a copy that builds without the template, once"
start
build --vendor "$D"
check_exit 0 $?
exists "$D/build.py"
mkdir -p "$CASE/client"
cp -R "$D" "$CASE/client/docs"
rm -f "$CASE/client/docs/index.html" "$CASE/client/docs/llms.txt"
(cd "$CASE" && env -i PATH="$PATH" HOME="$CASE" uv run -q "$CASE/client/docs/build.py") > "$OUT" 2>&1
check_exit 0 $?
exists "$CASE/client/docs/index.html"
exists "$CASE/client/docs/llms.txt"
contains "$CASE/client/docs/index.html" '<section class="doc" id="overview"'
"$CASE/client/docs/build.py" --vendor > "$OUT" 2>&1
check_exit 1 $?
contains "$OUT" "already vendored"

printf '\n%s passed, %s failed\n' "$PASS" "$FAIL"
[ "$FAIL" = 0 ]
